package de.omegazirkel.risingworld.shop;

public enum ShopErrorCode {
    NONE,
    INVALID_ARGUMENT,
    DUPLICATE_OFFER,
    OFFER_NOT_FOUND,
    OFFER_DISABLED,
    OWNER_MISMATCH,
    WALLET_UNAVAILABLE,
    PAYMENT_FAILED,
    PRICE_RESOLUTION_FAILED,
    CALLBACK_MISSING,
    INVENTORY_FULL,
    CALLBACK_FAILED,
    REFUND_FAILED
}
