
# possible values: OFF,FATAL,ERROR,WARN,INFO,DEBUG,TRACE,ALL
logLevel=ALL

# reload plugin settings when settings.properties changes
reloadOnChange=true

# chat command used to open/list/buy shop offers
shopCommand=shop

# send plugin welcome message to player on login
sendPluginWelcome=false

# system-shop offer file copied from system-offers.default.json on first run
systemOffersFile=system-offers.json
